title: Liz Hughes
remote_theme: "github/cayman"
nav:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/lizh7613/"
  - name: "GitHub"
    url: "https://github.com/lizh7613"
  - name: "Download CV"
    url: "/CV.pdf"
