title: Liz Hughes
remote_theme: pages-themes/cayman@v0.2.0
nav:
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/lizh7613/"
  - name: "GitHub"
    url: "https://github.com/lizh7613"
  - name: "Download CV"
    url: "/CV.pdf"
